#+TITLE: README
* org-mode configuration
#+FILETAGS: AI4KIDS
#+STARTUP: overview
#+STARTUP: hidestars
#+LANGUAGE: zh-CN

* Collection of my articles in learning Artifical Intelligence
** Motivation

When I started to learn machine learning, data mining or other knowledge related with artifical intelligence, I found the books were difficult to understand because they were filled with mathematics, algorithms, programming languages that I did not know yet.

So I decided to write down what I read as well as my comprehension about those ideas in my way.

The reason that I name this collection "AI for kids" just because I feel I were a kid when I try to learn those principles, equations, programs.

I hope I can grow up soon in this field and change this book to "AI for adults".

** Book? No.

A book should be sysmatically designed to detail a specific problem.

However, I am not sure how far I can go. Maybe the most important thing is "I am on the way".

So I will not call this a BOOK. Instead, I name it "Collection of articles".

** Why "AI"?

"AI" is really a huge concept that covers a lot of specific scientific or technical fields. For example, machine learning, data mining, natural language processing, robot, auto drive, etc.

I am not sure what I am going to read or discuss. So maybe a vague scope will urge me to walk along.

** How

Programs should be a good way to demonstrate  the obscure theory. I will host these programs in github as well as the collection of articles.

* License

This work\(i.e. all contents under current topic\) is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.

本作品\(即在当前主题下创作的所有内容\)采用知识共享 署名-非商业性使用-禁止演绎 4.0 国际 许可协议进行许可。访问 [http://creativecommons.org/licenses/by-nc-nd/4.0/](http://creativecommons.org/licenses/by-nc-nd/4.0/) 查看该许可协议。

